apiVersion: v1
kind: Service
metadata:
  name: list-test-service
spec:
  selector:
    app: list-test-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: list-test-app
spec:
  selector:
    matchLabels:
      app: list-test-app
  replicas: 5
  template:
    metadata:
      labels:
        app: list-test-app
    spec:
      containers:
      - name: list-test-app
        image: list
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
